{% set name = "hitea" %}
{% set version = "0.1.1" %}

package:
  name: hitea
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://github.com/parklab/HiTea/archive/{{ version }}.tar.gz
  md5: 2582c59ca891ff298346a5d00c1e01e0

build:
  number: 0
  noarch: python
  
requirements:
  host:
    - r-base >=3.4.1
    - r-ggplot2 =3.3.0
    - r-rcolorbrewer >=1.1
    - r-knitr ==1.27
    - r-rmarkdown >=2.1
    - bioconductor-genomicranges >=1.38.0
    - bioconductor-enrichedheatmap >=1.16.0
    - bedtools ==2.26.0
    - samtools ==1.10
    - numpy >=1.10
    - perl >=5.20
    - bwa ==0.7.17
    - pairtools ==0.3.0
    - parallel ==20200322

  run:
    - r-base >=3.4.1
    - r-ggplot2 ==3.3.0
    - r-rcolorbrewer >=1.1
    - r-knitr ==1.27
    - r-rmarkdown >=2.1
    - bioconductor-genomicranges >=1.38.0
    - bioconductor-enrichedheatmap >=1.16.0
    - numpy >=1.10
    - bedtools ==2.26.0
    - samtools ==1.10
    - bwa ==0.7.17
    - perl >=5.20
    - pairtools ==0.3.0
    - parallel ==20200322

test:
  commands:
    - samtools --version
    - bedtools --version
    - R --version
    - perl --version
    - python --version
    - pairtools parse --help
    - bwa
    - hitea
    - bash test.sh

about:
  home: https://github.com/parklab/HiTea
  license: MIT
  license_file: "LICENSE.txt"
  summary: computational tool to identify trasposable element insertions using Hi-C data
  license_family: MIT
